export type LearnItem = { emoji: string; ar: string; en: string; note?: string };
export type LearnCategory = { id: string; title: string; emoji: string; items: LearnItem[] };

// قوائم الكلمات الشائعة مصنّفة، لكل كلمة رمز توضيحي
export const WORD_CATEGORIES: LearnCategory[] = [
  {
    id: "family",
    title: "العائلة",
    emoji: "👨‍👩‍👧‍👦",
    items: [
      { emoji: "👨", ar: "أب", en: "Father" },
      { emoji: "👩", ar: "أم", en: "Mother" },
      { emoji: "👦", ar: "ابن", en: "Son" },
      { emoji: "👧", ar: "ابنة", en: "Daughter" },
      { emoji: "👴", ar: "جد", en: "Grandfather" },
      { emoji: "👵", ar: "جدة", en: "Grandmother" },
      { emoji: "👶", ar: "طفل", en: "Baby" },
      { emoji: "👫", ar: "صديق", en: "Friend" },
    ],
  },
  {
    id: "food",
    title: "الطعام",
    emoji: "🍎",
    items: [
      { emoji: "🍞", ar: "خبز", en: "Bread" },
      { emoji: "💧", ar: "ماء", en: "Water" },
      { emoji: "🍎", ar: "تفاحة", en: "Apple" },
      { emoji: "🍌", ar: "موز", en: "Banana" },
      { emoji: "🥛", ar: "حليب", en: "Milk" },
      { emoji: "🍚", ar: "أرز", en: "Rice" },
      { emoji: "🍗", ar: "دجاج", en: "Chicken" },
      { emoji: "☕", ar: "قهوة", en: "Coffee" },
    ],
  },
  {
    id: "animals",
    title: "الحيوانات",
    emoji: "🐱",
    items: [
      { emoji: "🐱", ar: "قطة", en: "Cat" },
      { emoji: "🐶", ar: "كلب", en: "Dog" },
      { emoji: "🐴", ar: "حصان", en: "Horse" },
      { emoji: "🐦", ar: "طائر", en: "Bird" },
      { emoji: "🐟", ar: "سمكة", en: "Fish" },
      { emoji: "🦁", ar: "أسد", en: "Lion" },
      { emoji: "🐘", ar: "فيل", en: "Elephant" },
      { emoji: "🐝", ar: "نحلة", en: "Bee" },
    ],
  },
  {
    id: "colors",
    title: "الألوان",
    emoji: "🌈",
    items: [
      { emoji: "🔴", ar: "أحمر", en: "Red" },
      { emoji: "🔵", ar: "أزرق", en: "Blue" },
      { emoji: "🟢", ar: "أخضر", en: "Green" },
      { emoji: "🟡", ar: "أصفر", en: "Yellow" },
      { emoji: "⚫", ar: "أسود", en: "Black" },
      { emoji: "⚪", ar: "أبيض", en: "White" },
      { emoji: "🟠", ar: "برتقالي", en: "Orange" },
      { emoji: "🟣", ar: "بنفسجي", en: "Purple" },
    ],
  },
  {
    id: "nature",
    title: "الطبيعة",
    emoji: "🌳",
    items: [
      { emoji: "☀️", ar: "شمس", en: "Sun" },
      { emoji: "🌙", ar: "قمر", en: "Moon" },
      { emoji: "⭐", ar: "نجمة", en: "Star" },
      { emoji: "🌳", ar: "شجرة", en: "Tree" },
      { emoji: "🌹", ar: "وردة", en: "Flower" },
      { emoji: "🌧️", ar: "مطر", en: "Rain" },
      { emoji: "🔥", ar: "نار", en: "Fire" },
      { emoji: "🏔️", ar: "جبل", en: "Mountain" },
    ],
  },
  {
    id: "actions",
    title: "أفعال أساسية",
    emoji: "🏃",
    items: [
      { emoji: "🍽️", ar: "يأكل", en: "Eat" },
      { emoji: "🥤", ar: "يشرب", en: "Drink" },
      { emoji: "😴", ar: "ينام", en: "Sleep" },
      { emoji: "🏃", ar: "يجري", en: "Run" },
      { emoji: "📖", ar: "يقرأ", en: "Read" },
      { emoji: "✍️", ar: "يكتب", en: "Write" },
      { emoji: "🗣️", ar: "يتكلم", en: "Speak" },
      { emoji: "👂", ar: "يستمع", en: "Listen" },
    ],
  },
  {
    id: "actions2",
    title: "أفعال يومية",
    emoji: "⚡",
    items: [
      { emoji: "🚶", ar: "يمشي", en: "Walk" },
      { emoji: "🚗", ar: "يقود", en: "Drive" },
      { emoji: "🛒", ar: "يشتري", en: "Buy" },
      { emoji: "💰", ar: "يبيع", en: "Sell" },
      { emoji: "🤔", ar: "يفكّر", en: "Think" },
      { emoji: "❤️", ar: "يحب", en: "Love" },
      { emoji: "😊", ar: "يبتسم", en: "Smile" },
      { emoji: "🎁", ar: "يعطي", en: "Give" },
      { emoji: "🙌", ar: "يأخذ", en: "Take" },
      { emoji: "🔎", ar: "يبحث", en: "Search" },
      { emoji: "🧠", ar: "يتعلّم", en: "Learn" },
      { emoji: "👩‍🏫", ar: "يعلّم", en: "Teach" },
    ],
  },
  {
    id: "actions3",
    title: "أفعال العمل",
    emoji: "💼",
    items: [
      { emoji: "💻", ar: "يعمل", en: "Work" },
      { emoji: "📞", ar: "يتصل", en: "Call" },
      { emoji: "📧", ar: "يرسل", en: "Send" },
      { emoji: "🤝", ar: "يقابل", en: "Meet" },
      { emoji: "📝", ar: "يخطّط", en: "Plan" },
      { emoji: "✅", ar: "ينهي", en: "Finish" },
      { emoji: "🏁", ar: "يبدأ", en: "Start" },
      { emoji: "🛠️", ar: "يصلح", en: "Fix" },
    ],
  },
  {
    id: "numbers",
    title: "الأرقام",
    emoji: "🔢",
    items: [
      { emoji: "1️⃣", ar: "واحد", en: "One" },
      { emoji: "2️⃣", ar: "اثنان", en: "Two" },
      { emoji: "3️⃣", ar: "ثلاثة", en: "Three" },
      { emoji: "4️⃣", ar: "أربعة", en: "Four" },
      { emoji: "5️⃣", ar: "خمسة", en: "Five" },
      { emoji: "6️⃣", ar: "ستة", en: "Six" },
      { emoji: "7️⃣", ar: "سبعة", en: "Seven" },
      { emoji: "8️⃣", ar: "ثمانية", en: "Eight" },
      { emoji: "9️⃣", ar: "تسعة", en: "Nine" },
      { emoji: "🔟", ar: "عشرة", en: "Ten" },
      { emoji: "💯", ar: "مئة", en: "Hundred" },
      { emoji: "🔢", ar: "ألف", en: "Thousand" },
    ],
  },
  {
    id: "time",
    title: "الوقت والأيام",
    emoji: "⏰",
    items: [
      { emoji: "☀️", ar: "اليوم", en: "Today" },
      { emoji: "🌅", ar: "غداً", en: "Tomorrow" },
      { emoji: "🌇", ar: "أمس", en: "Yesterday" },
      { emoji: "⏰", ar: "ساعة", en: "Hour" },
      { emoji: "⌚", ar: "دقيقة", en: "Minute" },
      { emoji: "📅", ar: "أسبوع", en: "Week" },
      { emoji: "🗓️", ar: "شهر", en: "Month" },
      { emoji: "🎉", ar: "سنة", en: "Year" },
      { emoji: "🌄", ar: "صباح", en: "Morning" },
      { emoji: "🌙", ar: "ليل", en: "Night" },
    ],
  },
  {
    id: "home",
    title: "المنزل",
    emoji: "🏠",
    items: [
      { emoji: "🏠", ar: "بيت", en: "House" },
      { emoji: "🚪", ar: "باب", en: "Door" },
      { emoji: "🪟", ar: "نافذة", en: "Window" },
      { emoji: "🛏️", ar: "سرير", en: "Bed" },
      { emoji: "🪑", ar: "كرسي", en: "Chair" },
      { emoji: "🍽️", ar: "طاولة", en: "Table" },
      { emoji: "🚿", ar: "حمّام", en: "Bathroom" },
      { emoji: "🍳", ar: "مطبخ", en: "Kitchen" },
    ],
  },
  {
    id: "body",
    title: "أجزاء الجسم",
    emoji: "🧍",
    items: [
      { emoji: "🧠", ar: "رأس", en: "Head" },
      { emoji: "👁️", ar: "عين", en: "Eye" },
      { emoji: "👃", ar: "أنف", en: "Nose" },
      { emoji: "👄", ar: "فم", en: "Mouth" },
      { emoji: "👂", ar: "أذن", en: "Ear" },
      { emoji: "✋", ar: "يد", en: "Hand" },
      { emoji: "🦶", ar: "قدم", en: "Foot" },
      { emoji: "❤️", ar: "قلب", en: "Heart" },
    ],
  },
  {
    id: "travel",
    title: "السفر",
    emoji: "✈️",
    items: [
      { emoji: "✈️", ar: "طائرة", en: "Airplane" },
      { emoji: "🎫", ar: "تذكرة", en: "Ticket" },
      { emoji: "🛂", ar: "جواز سفر", en: "Passport" },
      { emoji: "🏨", ar: "فندق", en: "Hotel" },
      { emoji: "🧳", ar: "حقيبة", en: "Suitcase" },
      { emoji: "🗺️", ar: "خريطة", en: "Map" },
      { emoji: "🚉", ar: "محطة", en: "Station" },
      { emoji: "🏖️", ar: "عطلة", en: "Holiday" },
    ],
  },
  {
    id: "transport",
    title: "المواصلات",
    emoji: "🚌",
    items: [
      { emoji: "🚗", ar: "سيارة", en: "Car" },
      { emoji: "🚌", ar: "حافلة", en: "Bus" },
      { emoji: "🚆", ar: "قطار", en: "Train" },
      { emoji: "🚕", ar: "تاكسي", en: "Taxi" },
      { emoji: "🚲", ar: "دراجة", en: "Bicycle" },
      { emoji: "🛵", ar: "دراجة نارية", en: "Motorbike" },
      { emoji: "⛴️", ar: "سفينة", en: "Ship" },
      { emoji: "🛣️", ar: "طريق", en: "Road" },
    ],
  },
  {
    id: "work",
    title: "المهن والعمل",
    emoji: "💼",
    items: [
      { emoji: "👨‍⚕️", ar: "طبيب", en: "Doctor" },
      { emoji: "👩‍🏫", ar: "معلّم", en: "Teacher" },
      { emoji: "👨‍🍳", ar: "طبّاخ", en: "Cook" },
      { emoji: "👮", ar: "شرطي", en: "Police officer" },
      { emoji: "👷", ar: "عامل", en: "Worker" },
      { emoji: "👨‍💻", ar: "مهندس", en: "Engineer" },
      { emoji: "🧑‍🌾", ar: "مزارع", en: "Farmer" },
      { emoji: "🏢", ar: "مكتب", en: "Office" },
    ],
  },
  {
    id: "health",
    title: "الصحة",
    emoji: "🩺",
    items: [
      { emoji: "🏥", ar: "مستشفى", en: "Hospital" },
      { emoji: "💊", ar: "دواء", en: "Medicine" },
      { emoji: "🤒", ar: "مريض", en: "Sick" },
      { emoji: "🤕", ar: "ألم", en: "Pain" },
      { emoji: "🌡️", ar: "حرارة", en: "Fever" },
      { emoji: "💉", ar: "حقنة", en: "Injection" },
      { emoji: "🩹", ar: "جرح", en: "Wound" },
      { emoji: "😀", ar: "صحة", en: "Health" },
    ],
  },
  {
    id: "shopping",
    title: "التسوق",
    emoji: "🛒",
    items: [
      { emoji: "🏪", ar: "متجر", en: "Shop" },
      { emoji: "💵", ar: "نقود", en: "Money" },
      { emoji: "🏷️", ar: "سعر", en: "Price" },
      { emoji: "💳", ar: "بطاقة", en: "Card" },
      { emoji: "🧾", ar: "فاتورة", en: "Receipt" },
      { emoji: "🎁", ar: "هدية", en: "Gift" },
      { emoji: "🛍️", ar: "كيس", en: "Bag" },
      { emoji: "📉", ar: "تخفيض", en: "Discount" },
    ],
  },
  {
    id: "clothes",
    title: "الملابس",
    emoji: "👕",
    items: [
      { emoji: "👕", ar: "قميص", en: "Shirt" },
      { emoji: "👖", ar: "بنطال", en: "Trousers" },
      { emoji: "👗", ar: "فستان", en: "Dress" },
      { emoji: "🧥", ar: "معطف", en: "Coat" },
      { emoji: "👟", ar: "حذاء", en: "Shoes" },
      { emoji: "🧦", ar: "جوارب", en: "Socks" },
      { emoji: "🧢", ar: "قبعة", en: "Hat" },
      { emoji: "🧣", ar: "وشاح", en: "Scarf" },
    ],
  },
  {
    id: "weather",
    title: "الطقس",
    emoji: "🌤️",
    items: [
      { emoji: "☀️", ar: "مشمس", en: "Sunny" },
      { emoji: "🌧️", ar: "ممطر", en: "Rainy" },
      { emoji: "❄️", ar: "ثلج", en: "Snow" },
      { emoji: "🌬️", ar: "رياح", en: "Wind" },
      { emoji: "☁️", ar: "غائم", en: "Cloudy" },
      { emoji: "🥶", ar: "بارد", en: "Cold" },
      { emoji: "🥵", ar: "حار", en: "Hot" },
      { emoji: "🌈", ar: "قوس قزح", en: "Rainbow" },
    ],
  },
  {
    id: "feelings",
    title: "المشاعر",
    emoji: "😊",
    items: [
      { emoji: "😊", ar: "سعيد", en: "Happy" },
      { emoji: "😢", ar: "حزين", en: "Sad" },
      { emoji: "😡", ar: "غاضب", en: "Angry" },
      { emoji: "😨", ar: "خائف", en: "Afraid" },
      { emoji: "😴", ar: "متعب", en: "Tired" },
      { emoji: "😍", ar: "متحمّس", en: "Excited" },
      { emoji: "😌", ar: "هادئ", en: "Calm" },
      { emoji: "😲", ar: "متفاجئ", en: "Surprised" },
    ],
  },
  {
    id: "school",
    title: "المدرسة",
    emoji: "🎓",
    items: [
      { emoji: "🏫", ar: "مدرسة", en: "School" },
      { emoji: "📚", ar: "كتاب", en: "Book" },
      { emoji: "✏️", ar: "قلم", en: "Pen" },
      { emoji: "📓", ar: "دفتر", en: "Notebook" },
      { emoji: "🧑‍🎓", ar: "طالب", en: "Student" },
      { emoji: "📝", ar: "امتحان", en: "Exam" },
      { emoji: "🧮", ar: "رياضيات", en: "Mathematics" },
      { emoji: "🗣️", ar: "درس", en: "Lesson" },
    ],
  },
  {
    id: "city",
    title: "المدينة",
    emoji: "🏙️",
    items: [
      { emoji: "🏙️", ar: "مدينة", en: "City" },
      { emoji: "🏦", ar: "بنك", en: "Bank" },
      { emoji: "📮", ar: "بريد", en: "Post office" },
      { emoji: "🅿️", ar: "موقف", en: "Parking" },
      { emoji: "🍽️", ar: "مطعم", en: "Restaurant" },
      { emoji: "⛪", ar: "كنيسة", en: "Church" },
      { emoji: "🌳", ar: "حديقة", en: "Park" },
      { emoji: "🚦", ar: "إشارة", en: "Traffic light" },
    ],
  },
  {
    id: "tech",
    title: "التكنولوجيا",
    emoji: "💻",
    items: [
      { emoji: "📱", ar: "هاتف", en: "Phone" },
      { emoji: "💻", ar: "حاسوب", en: "Computer" },
      { emoji: "🌐", ar: "إنترنت", en: "Internet" },
      { emoji: "📧", ar: "بريد إلكتروني", en: "Email" },
      { emoji: "🔑", ar: "كلمة مرور", en: "Password" },
      { emoji: "📷", ar: "كاميرا", en: "Camera" },
      { emoji: "🔋", ar: "بطارية", en: "Battery" },
      { emoji: "📶", ar: "شبكة", en: "Network" },
    ],
  },
  {
    id: "phrases",
    title: "عبارات يومية",
    emoji: "💬",
    items: [
      { emoji: "👋", ar: "مرحباً", en: "Hello" },
      { emoji: "🌅", ar: "صباح الخير", en: "Good morning" },
      { emoji: "🌙", ar: "مساء الخير", en: "Good evening" },
      { emoji: "🙏", ar: "شكراً", en: "Thank you" },
      { emoji: "🙂", ar: "من فضلك", en: "Please" },
      { emoji: "😅", ar: "آسف", en: "Sorry" },
      { emoji: "👌", ar: "حسناً", en: "Okay" },
      { emoji: "❓", ar: "كيف حالك؟", en: "How are you?" },
      { emoji: "🆗", ar: "أنا بخير", en: "I am fine" },
      { emoji: "🤷", ar: "لا أفهم", en: "I don't understand" },
      { emoji: "🐢", ar: "من فضلك ببطء", en: "Slowly please" },
      { emoji: "👋", ar: "إلى اللقاء", en: "Goodbye" },
    ],
  },
  {
    id: "questions",
    title: "أدوات السؤال",
    emoji: "❓",
    items: [
      { emoji: "❓", ar: "ماذا", en: "What" },
      { emoji: "📍", ar: "أين", en: "Where" },
      { emoji: "⏰", ar: "متى", en: "When" },
      { emoji: "🤔", ar: "لماذا", en: "Why" },
      { emoji: "🙋", ar: "من", en: "Who" },
      { emoji: "🛠️", ar: "كيف", en: "How" },
      { emoji: "🔢", ar: "كم", en: "How much" },
      { emoji: "↔️", ar: "أيّ", en: "Which" },
    ],
  },
  {
    id: "adjectives",
    title: "صفات شائعة",
    emoji: "⭐",
    items: [
      { emoji: "⬆️", ar: "كبير", en: "Big" },
      { emoji: "⬇️", ar: "صغير", en: "Small" },
      { emoji: "✅", ar: "جيد", en: "Good" },
      { emoji: "❌", ar: "سيّئ", en: "Bad" },
      { emoji: "🆕", ar: "جديد", en: "New" },
      { emoji: "🏚️", ar: "قديم", en: "Old" },
      { emoji: "⚡", ar: "سريع", en: "Fast" },
      { emoji: "🐌", ar: "بطيء", en: "Slow" },
      { emoji: "💪", ar: "قوي", en: "Strong" },
      { emoji: "🍃", ar: "سهل", en: "Easy" },
      { emoji: "🧗", ar: "صعب", en: "Difficult" },
      { emoji: "💎", ar: "جميل", en: "Beautiful" },
    ],
  },
  {
    id: "conversation",
    title: "التواصل والمحادثة",
    emoji: "🗨️",
    items: [
      { emoji: "💡", ar: "فكرة", en: "Idea" },
      { emoji: "💬", ar: "رأي", en: "Opinion" },
      { emoji: "🤝", ar: "موافقة", en: "Agreement" },
      { emoji: "🙅", ar: "اختلاف", en: "Disagreement" },
      { emoji: "🔁", ar: "كرّر", en: "Repeat" },
      { emoji: "🗣️", ar: "اشرح", en: "Explain" },
      { emoji: "🧩", ar: "مثال", en: "Example" },
      { emoji: "📖", ar: "معنى", en: "Meaning" },
      { emoji: "✅", ar: "صحيح", en: "Correct" },
      { emoji: "⚠️", ar: "خطأ", en: "Mistake" },
      { emoji: "🤔", ar: "ربما", en: "Maybe" },
      { emoji: "🎯", ar: "بالتأكيد", en: "Certainly" },
    ],
  },
  {
    id: "directions",
    title: "الاتجاهات والأماكن",
    emoji: "🧭",
    items: [
      { emoji: "⬅️", ar: "يسار", en: "Left" },
      { emoji: "➡️", ar: "يمين", en: "Right" },
      { emoji: "⬆️", ar: "مستقيم", en: "Straight" },
      { emoji: "📍", ar: "قريب", en: "Near" },
      { emoji: "🌄", ar: "بعيد", en: "Far" },
      { emoji: "⬆️", ar: "فوق", en: "Above" },
      { emoji: "⬇️", ar: "تحت", en: "Below" },
      { emoji: "↔️", ar: "بين", en: "Between" },
      { emoji: "🚪", ar: "بجانب", en: "Next to" },
      { emoji: "🪞", ar: "مقابل", en: "Opposite" },
      { emoji: "🛣️", ar: "تقاطع", en: "Intersection" },
      { emoji: "📌", ar: "عنوان", en: "Address" },
    ],
  },
  {
    id: "emergency",
    title: "الطوارئ والمساعدة",
    emoji: "🆘",
    items: [
      { emoji: "🆘", ar: "النجدة", en: "Help" },
      { emoji: "🚨", ar: "طوارئ", en: "Emergency" },
      { emoji: "🚑", ar: "سيارة إسعاف", en: "Ambulance" },
      { emoji: "👮", ar: "الشرطة", en: "Police" },
      { emoji: "🔥", ar: "حريق", en: "Fire" },
      { emoji: "📱", ar: "اتصل", en: "Call" },
      { emoji: "🧭", ar: "ضائع", en: "Lost" },
      { emoji: "⚠️", ar: "خطر", en: "Danger" },
      { emoji: "🛑", ar: "توقّف", en: "Stop" },
      { emoji: "🏥", ar: "أحتاج طبيباً", en: "I need a doctor" },
      { emoji: "📄", ar: "فقدت جواز سفري", en: "I lost my passport" },
      { emoji: "📍", ar: "أين أنا؟", en: "Where am I?" },
    ],
  },
  {
    id: "daily-needs",
    title: "احتياجات يومية",
    emoji: "🧺",
    items: [
      { emoji: "🔌", ar: "شاحن", en: "Charger" },
      { emoji: "🔑", ar: "مفتاح", en: "Key" },
      { emoji: "🧴", ar: "صابون", en: "Soap" },
      { emoji: "🪥", ar: "فرشاة أسنان", en: "Toothbrush" },
      { emoji: "🧻", ar: "مناديل", en: "Tissues" },
      { emoji: "☂️", ar: "مظلّة", en: "Umbrella" },
      { emoji: "🧾", ar: "موعد", en: "Appointment" },
      { emoji: "📦", ar: "طرد", en: "Package" },
      { emoji: "🛗", ar: "مصعد", en: "Elevator" },
      { emoji: "🪜", ar: "درج", en: "Stairs" },
      { emoji: "🔒", ar: "مغلق", en: "Closed" },
      { emoji: "🔓", ar: "مفتوح", en: "Open" },
    ],
  },
  {
    id: "confusing-words",
    title: "كلمات يكثر الخطأ بها",
    emoji: "🧠",
    items: [
      {
        emoji: "✅",
        ar: "يقبل",
        en: "Accept",
        note: "تُستخدم عند الموافقة أو استلام شيء، وليست بمعنى الاستثناء.",
      },
      {
        emoji: "➖",
        ar: "باستثناء",
        en: "Except",
        note: "تُستخدم لإخراج شخص أو شيء من المجموعة.",
      },
      {
        emoji: "📥",
        ar: "يستعير",
        en: "Borrow",
        note: "عندما تأخذ شيئاً مؤقتاً من شخص ثم تعيده.",
      },
      {
        emoji: "📤",
        ar: "يُعير",
        en: "Lend",
        note: "عندما تعطي شخصاً شيئاً مؤقتاً ليعيده لك.",
      },
      {
        emoji: "🧍",
        ar: "شخص",
        en: "Person",
        note: "لشخص واحد؛ جمعها أشخاص.",
      },
      {
        emoji: "👥",
        ar: "أشخاص",
        en: "People",
        note: "جمع شائع لكلمة شخص، وليست للمكان.",
      },
      {
        emoji: "📍",
        ar: "مكان",
        en: "Place",
        note: "موقع أو موضع، وليس شخصاً.",
      },
      {
        emoji: "🗣️",
        ar: "يقول",
        en: "Say",
        note: "يركّز على الكلام الذي قيل، وغالباً يأتي بعده الكلام مباشرة.",
      },
      {
        emoji: "👤",
        ar: "يخبر",
        en: "Tell",
        note: "يركّز على الشخص الذي نخبره، وغالباً يأتي بعده شخص.",
      },
      {
        emoji: "👀",
        ar: "يرى",
        en: "See",
        note: "رؤية شيء بصورة طبيعية من دون تركيز مقصود.",
      },
      {
        emoji: "📺",
        ar: "يشاهد",
        en: "Watch",
        note: "نظر مقصود لشيء متحرك أو يستمر مدة.",
      },
      {
        emoji: "🔎",
        ar: "ينظر",
        en: "Look",
        note: "توجيه العين عمداً نحو شيء محدد.",
      },
      {
        emoji: "👂",
        ar: "يسمع",
        en: "Hear",
        note: "وصول الصوت إلى أذنك من دون قصد.",
      },
      {
        emoji: "🎧",
        ar: "يستمع",
        en: "Listen",
        note: "الانتباه إلى الصوت بقصد وتركيز.",
      },
      {
        emoji: "🏠",
        ar: "منزل",
        en: "House",
        note: "المبنى المادي الذي يسكن فيه الناس.",
      },
      {
        emoji: "❤️",
        ar: "وطن أو بيت",
        en: "Home",
        note: "المكان الذي تعيش فيه وتشعر أنه بيتك، وليس المبنى فقط.",
      },
      {
        emoji: "💼",
        ar: "عمل",
        en: "Work",
        note: "نشاط أو مهام تقوم بها، ولا تُجمع عادةً بهذا المعنى.",
      },
      {
        emoji: "👔",
        ar: "وظيفة",
        en: "Job",
        note: "منصب أو وظيفة محددة ويمكن عدّها.",
      },
      {
        emoji: "📚",
        ar: "يتعلّم",
        en: "Learn",
        note: "يكتسب الطالب معرفة أو مهارة.",
      },
      {
        emoji: "👩‍🏫",
        ar: "يعلّم",
        en: "Teach",
        note: "ينقل المعلّم المعرفة إلى شخص آخر.",
      },
      {
        emoji: "🧠",
        ar: "يتذكّر",
        en: "Remember",
        note: "تبقى المعلومة في الذاكرة أو تعود إليها.",
      },
      {
        emoji: "🌫️",
        ar: "ينسى",
        en: "Forget",
        note: "لا يتذكّر المعلومة أو لا يقوم بما كان مقرراً.",
      },
      {
        emoji: "⏳",
        ar: "منذ مدة",
        en: "For",
        note: "تُستخدم مع مدة زمنية مثل ساعتين أو ثلاث سنوات.",
      },
      {
        emoji: "📅",
        ar: "منذ وقت محدد",
        en: "Since",
        note: "تُستخدم مع نقطة بداية مثل الاثنين أو عام 2020.",
      },
    ],
  },
];

// الضمائر مع رمز توضيحي يبيّن المقصود
export const PRONOUNS: LearnItem[] = [
  { emoji: "🙋", ar: "أنا", en: "I" },
  { emoji: "👉", ar: "أنتَ", en: "You (m)" },
  { emoji: "👉", ar: "أنتِ", en: "You (f)" },
  { emoji: "👨", ar: "هو", en: "He" },
  { emoji: "👩", ar: "هي", en: "She" },
  { emoji: "🧑‍🤝‍🧑", ar: "نحن", en: "We" },
  { emoji: "👥", ar: "أنتم", en: "You (pl)" },
  { emoji: "👫", ar: "هم", en: "They" },
  { emoji: "📦", ar: "هذا", en: "This" },
  { emoji: "📦", ar: "ذلك", en: "That" },
];
